[package]
name = "rust-webrtc-test"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
async-std = { version = "1.6.5", features = ["attributes"] }
async-tungstenite = { version = "0.8.0", features = ["async-std-runtime"] }
futures = "0.3.6"
gstreamer = { version = "0.16.3", features = ["v1_18"] }
gstreamer-audio = { version = "0.16.3", features = ["v1_18"] }
gstreamer-rtp = { version = "0.16.3", features = ["v1_18"] }
gstreamer-sdp = { version = "0.16.3", features = ["v1_18"] }
gstreamer-video = { version = "0.16.3", features = ["v1_18"] }
gstreamer-webrtc = { version = "0.16.3", features = ["v1_18"] }
serde = "1.0.116"
serde_derive = "1.0.116"
serde_json = "1.0.58"
structopt = { version = "0.3.19", default-features = false }
