edition = "2018"
use_try_shorthand = true
use_field_init_shorthand = true
merge_imports = true
reorder_impl_items = true
normalize_comments = true
format_strings = true
format_code_in_doc_comments = true
condense_wildcard_suffixes = true
